; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; 0 — None
; 1 — Error
; 2 — Warn
; 3 — Info (current for all envs)
; 4 — Debug
; 5 — Verbose

[base]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit BNO08x @ ^1.2.3
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    madhephaestus/ESP32Servo
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git

[env:car]
extends = base
build_flags =
    ${base.build_flags}
    -DCORE_DEBUG_LEVEL=2
monitor_echo = yes

[env:test]
extends = base
build_flags =
    ${base.build_flags}
    -DCORE_DEBUG_LEVEL=3

[env:debug]
extends = base
build_flags =
    ${base.build_flags}
    -DCORE_DEBUG_LEVEL=4
