#include "runtime_config.h"

RuntimeConfig rtConfig = {
    .throttleScale          = THROTTLE_SCALE,
    .throttleDeadband       = THROTTLE_Deadband,
    .followDistanceCm       = FOLLOW_DISTANCE_CM,
    .maxDistanceCm          = MAX_DISTANCE_CM,
    .minSpeedMph            = MIN_SPEED_MPH,
    .maxSpeedMph            = MAX_SPEED_MPH,
    .kp                     = THROTTLE_PID_KP,
    .ki                     = THROTTLE_PID_KI,
    .kd                     = THROTTLE_PID_KD,
    .smoothAlpha            = THROTTLE_SMOOTH_ALPHA,
    .steeringTrim           = STEERING_TRIM,
    .steeringKp             = STEERING_PID_KP,
    .steeringKi             = STEERING_PID_KI,
    .steeringMax            = STEERING_MAX,
    .uwbOutlierRejectCm     = UWB_OUTLIER_REJECT_CM,
    .fusedEncR              = RPM_FUSED_ENC_R,
    .fusedHallR             = RPM_FUSED_HALL_R,
    .fusedRampStartMph      = RPM_FUSED_ENC_RAMP_START_MPH,
    .fusedRampEndMph        = RPM_FUSED_ENC_RAMP_END_MPH,
    .fused2QSpeed           = RPM_FUSED2_Q_SPEED,
    .fused2QBias            = RPM_FUSED2_Q_BIAS,
};
