#include "runtime_config.h"

RuntimeConfig rtConfig = {
    .throttleScale          = THROTTLE_SCALE,
    .throttleDeadband       = THROTTLE_Deadband,
    .followDistanceCm       = FOLLOW_DISTANCE_CM,
    .maxDistanceCm          = MAX_DISTANCE_CM,
    .minSpeedMph            = MIN_SPEED_MPH,
    .maxSpeedMph            = MAX_SPEED_MPH,
    .kp                     = THROTTLE_PID_KP,
    .ki                     = THROTTLE_PID_KI,
    .kd                     = THROTTLE_PID_KD,
    .throttleFfK            = THROTTLE_FF_K,
    .smoothAlpha            = THROTTLE_SMOOTH_ALPHA,
    .steeringTrim           = 0.0f,
    .steeringKp             = STEERING_PID_KP,
    .steeringKi             = STEERING_PID_KI,
    .steeringMax            = STEERING_MAX,
    .uwbKalmanQ             = UWB_KALMAN_Q,
    .uwbKalmanR             = UWB_KALMAN_R,
    .uwbOutlierRejectCm     = UWB_OUTLIER_REJECT_CM,
    .sensorTimeoutSec       = FUSION_SENSOR_TIMEOUT_SEC,
    .fusionRUwb             = FUSION_KALMAN_R_UWB,
    .fusionRCamera          = FUSION_KALMAN_R_CAMERA,
    .fusionStaleUncertainty = FUSION_STALE_UNCERTAINTY,
    .fusionInnovMeanAlpha   = FUSION_INNOV_MEAN_ALPHA,
    .fusionInnovEwmaAlpha   = FUSION_INNOV_EWMA_ALPHA,
    .testThrottle           = 0.0f,
};
